spring.application.name=OSApiApplication
spring.datasource.url=jdbc:mysql://172.16.0.30:3306/gar_osapi?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=gar
spring.datasource.password=2diSenai